LOG_LEVEL: "debug"
MESSAGE_BUS_DRIVER: "pubsub"
BUS_PREFIX: "dev."
NATS_URL: "nats://nats:4222"
PUBSUB_BATCH_MAX_MS: "20"
PUBSUB_ENSURE_MODE: "on-publish-fail"
PUBSUB_PUBLISH_TIMEOUT_MS: "2000"
TWITCH_BOT_USERNAME: "bitbrat_the_ai"
TWITCH_CHANNELS: "gonj_the_unjust"