PUBSUB_BATCH_MAX_MS: "20"
PUBSUB_ENSURE_MODE: "on-publish-fail"
PUBSUB_PUBLISH_TIMEOUT_MS: "0"
TWITCH_BOT_USERNAME: "bitbrat_the_ai"
TWITCH_CHANNELS: "gonj_the_unjust"
DISCORD_GUILD_ID: "1324629154695483422"
DISCORD_CHANNELS: "1324629154695483426"
DISCORD_USE_TOKEN_STORE: "false"
DISCORD_ALLOW_ENV_FALLBACK: "true"
DISCORD_TOKEN_POLL_MS: "60000"
DISCORD_ENABLED: true