LOG_LEVEL: "debug"
MESSAGE_BUS_DRIVER: "pubsub"
BUS_PREFIX: "dev."
NATS_URL: "nats://nats:4222"
PUBSUB_BATCH_MAX_MS: "20"
PUBSUB_ENSURE_MODE: "on-publish-fail"
PUBSUB_PUBLISH_TIMEOUT_MS: "0"
TWITCH_BOT_USERNAME: "bitbrat_the_ai"
TWITCH_CHANNELS: "gonj_the_unjust"
DISCORD_ENABLED: "false"
DISCORD_GUILD_ID: "1324629154695483422"
DISCORD_CHANNELS: "1324629154695483426"
DISCORD_USE_TOKEN_STORE: "false"
DISCORD_ALLOW_ENV_FALLBACK: "true"
DISCORD_BOT_TOKEN: ""
DISCORD_TOKEN_POLL_MS: "60000"